### ISSUE TITLE
resnet&swintransformer

### ISSUE THREAD

**Issue by haoaZ** [ziplab/SN-Net#1]
Hello, has the code sewn by resnet and swing transformer not been released?

**Comment by HubHop** [comment]
Hi @haoaZ, thanks for your question. Here you go! 👉 https://github.com/ziplab/SN-Net/tree/main/stitching_resnet_swin

**Comment by haoaZ** [comment]
thanks，I was careless and didn't see it，hh

**Comment by haoaZ** [comment]
Thank you for your reply
