### ISSUE TITLE
Error from the evaluation of Resnet18&swin ti

### ISSUE THREAD

**Issue by TanachaiAnakewat** [ziplab/SN-Net#5]
I wanted to evaluate the stitched model using the pre-trained weight provided in [here](https://github.com/ziplab/SN-Net/tree/main/stitching_resnet_swin). I have downloaded the consequences and saved them under /checkpoint. I could run the program but it stopped in the middle after finishing the 781 Test.

Here is the command I got the error from:
```
./distributed_train.sh 1 \
[path/to/imagenet] \
-b 128 \
--stitch_config configs/resnet18_swin_ti.json \
--sched cosine \
--epochs 30 \
--lr 0.05 \
--amp --remode pixel \
--reprob 0.6 \
--aa rand-m9-mstd0.5-inc1 \
--resplit --split-bn -j 10 --dist-bn reduce \
--resume checkpoint/resnet18_swin_ti.pth --eval
``` 
and i got these errors:
```python
Traceback (most recent call last):
  File "SN-Net/stitching_resnet_swin/train.py", line 1186, in <module>
    main()
  File "SN-Net/stitching_resnet_swin/train.py", line 847, in main
    validate(
  File "/SN-Net/stitching_resnet_swin/train.py", line 1139, in validate
    loss = loss_fn(output, target)
  File ".pyenv/versions/anaconda3-2023.03/envs/snnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File ".pyenv/versions/anaconda3-2023.03/envs/snnet/lib/python3.9/site-packages/torch/nn/modules/loss.py", line 1164, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File ".pyenv/versions/anaconda3-2023.03/envs/snnet/lib/python3.9/site-packages/torch/nn/functional.py", line 3014, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: CUDA error: device-side assert triggered
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0
``` 
Env (same as ReadMe):
torch==1.12.1+cu113
torchvision==0.13.1+cu113 
torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113

**Comment by HubHop** [comment]
Hi @TanachaiAnakewat, thank you for your interests! I just ran the code with the same command on my local RTX3090 machine. It can run without any issues. Can you please double-check the number of GPUs available on your machine? It seems the error is related to distributed training.

**Comment by TanachaiAnakewat** [comment]
@HubHop Thank you for your kind response! I have tried to debug and got this error .
```python
./aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [14,0,0] Assertion `t >= 0 && t < n_classes` failed
``` 
So I added `print("batch_idx: {} target min:{},target max:{}".format(batch_idx,target.min(), target.max()))`  at [train.py inside validate ](https://github.com/ziplab/SN-Net/blob/main/stitching_resnet_swin/train.py#L1138) where the error occurs, according to this [discussion](https://discuss.pytorch.org/t/assertion-t-0-t-n-classes-failed-error/133794/2)

And I got this 
```
batch_idx: 1 target min:0,target max:0
batch_idx: 2 target min:0,target max:0
.
.

batch_idx: 388 target min:0,target max:0
batch_idx: 389 target min:0,target max:0
batch_idx: 390 target min:0,target max:1
batch_idx: 391 target min:1,target max:4
batch_idx: 392 target min:4,target max:7
.
.
batch_idx: 779 target min:995,target max:997
batch_idx: 780 target min:997,target max:1000
``` 
so at the batch_idx = 781, the value of target max is probably > 1000 which gives out this error. Do you have any idea about this? Thank you!

**Comment by TanachaiAnakewat** [comment]
Just found out that it was the problem with my data folder structure! Thank you

**Comment by HubHop** [comment]
Great! I will close this issue. If you have futher questions, please feel free to post here.
